### PR TITLE
Use generichash to derive the key

### PR DESCRIPTION
**Pull request by mcollina**
Fixes https://github.com/mcollina/fastify-secure-session/issues/1.

@emilabyes can you review this? I hope it address your concerns! Thanks for the nitpicking, I was planning on sending it to you or @mafintosh for review!

### CODE REVIEW

**Comment by emilbayes** [comment]
Yes, `crypto_generichash` does not add any security in this case, since it's a fast hash function. What you're looking for is password hashing, since that class of hash functions are called "key-derivation function" (KDF), and allows one to "stretch" a weak key (low entropy) to a stronger key. However that adds extra computation burden, and these keys are not meant for humans to remember, but rather production secrets that you might keep in a configuration file, parameter store or secure vault. I think the best course of action is to generate a key for the user, eg. as a seperate function using `randombytes_buf`, and help them persist it.

**Comment by mcollina** [comment]
From a dev UX perspective, it's way better to compute this at startup rather than at buildtime. This is (typically) a secret not well protected and distributed together with the source code. What you mention is __probably the best way to do it__, but it will create a lot of friction for the users. Other solutions on npm use this same approach.

Ideally this module should provide both ways: one that generates a binary file containing a true random secret, and an easier (but less secure path) doing something at startup time.

Should I use https://www.npmjs.com/package/sodium-native#crypto_hash_sha256output-input to derive the key?

**Comment by emilbayes** [comment]
No, that hash function is a lot weaker. What you say about build vs startup time is at odds with my philosophy regarding this, as there in my experience will always be production secrets that need to be managed (build time), and this is just another of those. A compromise could be: use `crypto_pwhash` at startup time, with the moderate settings and a salt that you embed in your module. This might add a couple of seconds to startup but greatly increases security. It is not great, but it is better than using a fast hash function such as Blake2b ('crypto_generichash`) or the SHA families of functions. The fast hash functions add a false sense of security in this use-case.

The threat model here is that you share the token with users, malicious or not, so they have the data available for offline cracking. Since the data contained in the session token is somewhat predictable (possible content is not random, but structured) there are only so many plain texts that the cipher text can map to. Also, if the key is chosen by a human, then the set of keys that an adversary would try is a lot smaller compared to a random key (high entropy), and therefore the cracking time is a lot less than it should be. All of this of course assumes that the target is worth attacking, but a false sense of security is worse than no security :)

**Comment by mcollina** [comment]
@emilbayes I've added the static key generation and handling, check it out!

**Comment by emilbayes** [comment]
Looks good! :)

**Pull request merged**
