### PR TITLE
malformed client cookie causes uncaught exception

### PR DESCRIPTION
**Pull request by sreekotay**
added lines 85-89 at line 85 to correct malformed client cookie uncaught exception (missing ';' in cookie caused the issue)

### CODE REVIEW

**Comment by mcollina** [comment]
also CI is failing

**Comment by sreekotay** [comment]
whoops!  will see why.... ah.  formatting mismatch.  my bad - let me address.
As for unit test - let me see how - this one odd, because the faillure relies on a client set cookie, not a server set cookie.  so not sure how

**Comment by sreekotay** [comment]
Ok PR is good but for unit test (was failing because of style guide mismatches).
Not sure how to build unit test for this case - happy to do the work and suggestions welcome.

**Comment by mcollina** [comment]
I think you can just duplicate this file https://github.com/mcollina/fastify-secure-session/blob/master/test/key.js and pass in a non-ok cookie.

**Comment by mcollina** [comment]
Fixed in #20

**Pull request closed without merging**
